### ISSUE TITLE
This is a place to talk about the meeting schedule and get reminders/announcements

### ISSUE THREAD

**Issue by sandhawke** [swicg/general#2]
This is a place to announce meetings, and briefly comment on them.   Watch this if you want reminders and announcements.   Until we come up with something better.

**Comment by sandhawke** [comment]
Reminder: meeting in 2.5 hours https://www.w3.org/wiki/SocialCG/2017-05-19

Survey of future weekly meeting times: http://doodle.com/poll/rnnsf2y2fgmiq8zb

**Comment by sandhawke** [comment]
Next meeting is tomorrow.    https://www.w3.org/wiki/SocialCG/2017-05-31

If this posting was useful to you, please give it a thumbs up.

**Comment by sandhawke** [comment]
Next meeting is tomorrow.  https://www.w3.org/wiki/SocialCG/2017-06-07

(I just added my regrets to the agenda -- at an all day meeting about combating fake news)

**Comment by sandhawke** [comment]
Next meeting is in about an hour, sorry I was sick and didn't post yesterday: https://www.w3.org/wiki/SocialCG/2017-06-14

(Still room for more agenda items)

Also, I posted last week's minutes at https://www.w3.org/wiki/SocialCG/2017-06-07/minutes  (It's pretty easy using http://pandoc.amy.gy/)

**Comment by capjamesg** [comment]
I am closing this Issue since we are announcing meetings through the W3C website at https://w3.org/community/socialcg/. Thank you for maintaining this, @sandhawke!

**Comment by TallTed** [comment]
@capjamesg — Could the meetings also be announced through the W3C Calendar, as many (if not most, though not all) other WGs and CGs and IGs are doing now, so interested parties can subscribe to the relevant ICS?
