### ISSUE TITLE
Possible typos for LDN

### ISSUE THREAD

**Issue by shujikamitsuna** [swicg/general#26]
Dear Sir and Madam

This is Shuji Kamitsuna@Japan.

"Linked Data Notifications" Japanese translation is available now.
http://www.asahi-net.or.jp/~ax2s-kmtn/internet/link/REC-ldn-20170502.html
 --> reported to w3c-translators@w3.org already.

Thank you for the great recommendation!

I found some possible typos:

(1) Status of This Document - "Sep 5 22 2017" might be "Sep 5 2017" or "Sep 22 2017".
(2) Sec. 1.1 - "complimentary" might be "complementary".

Best Regards,

**Comment by nightpool** [comment]
Thanks for the translation! Would you mind reporting such issues here: https://github.com/w3c/ldn/issues ?

**Comment by shujikamitsuna** [comment]
Dear nightpool,

Done.
Thank you!

Best regards,
