### ISSUE TITLE
RESOLUTION: This is currently the primary issue tracker for SWICG

### ISSUE THREAD

**Issue by gobengo** [swicg/general#27]
This is the only issue tracker I could find for https://www.w3.org/community/socialcg/

However, it's not explicitly linked as such from that w3c CG page. (It's linked as 'GitHub', but I wasn't sure how much of the GitHub functionality should be used vs things hosted at w3c or cloud.w3c).

I have no objections to this resolution as long as no one else does.

If this resolution passes, we can always propose to change issue trackers later. My only goal is to clarify the best place to file issues and the issue queue from which we should work on them.

ttl: 2 weeks (enough time for each of the SWIG meeting times to pass)

**How to Vote**

In favor: 👍 emoji on this github issue
Against: 👎 emoji on this github issue

**Next Steps**

SocialCG meetings can try to use primary issue trackers as a work queue / [kanban](https://en.wikipedia.org/wiki/Kanban).

AFAI remember, SocialWG never had a great-feeling process for managing issues. On the other hand, I remember everyone doing the best they could to triage hundreds of issues as best we can. Since then, I've thought a lot about how a distributed team of mostly volunteers can collaboratively work a queue. Some tools we could use are voting (to prioritize jobs) and bounties (to incentivize work).

**Comment by gobengo** [comment]
functionally, it seems like much discussion of 'issues' happens on https://socialhub.activitypub.rocks. So it's not wrong to vote against this resolution with an objection that we should actually consider that the issue tracker, and we can evolve that forum structure to have a clear 'topic' or tag for different *kinds* of issues.

**Comment by gobengo** [comment]
Reminder that this exists. Raise any objections in the next week.

**Comment by gobengo** [comment]
I hope that eventually this could be federated via https://fedeproxy.eu/

**Comment by hellekin** [comment]
I'm completely in favor of using a federated issue tracker when it's ready.

In the meantime I had already proposed to use the github-discourse bridge for issues from https://github.com/w3c/activitypub but unfortunately the first tests a few months ago where a bit inconclusive and I did not manage to take the time to do it again. Maybe it's a good moment to try again.

See https://github.com/discourse/discourse-github

**Comment by gobengo** [comment]
In today's call, I brought this up, and other people helped me remember about these other subproject-specific issue trackers, which I had not meant to resolve against using:
* ActivityPub: https://github.com/w3c/activitypub/issues
* ActivityStreams2: https://github.com/w3c/activitystreams/issues

Anyone else, please help me remember if I forgot others.

**Comment by gobengo** [comment]
I'm considering closing this resolution or revising it.

See new note: https://socialhub.activitypub.rocks/t/social-cg-issue-trackers/1648

**Comment by aschrijver** [comment]
> In the meantime I had already proposed to use the github-discourse bridge

@hellekin I think the github bridge was scaled down in functionality it provides. In theory it is a nice thing, I've seen it working.

**Comment by sebilasse** [comment]
Not sure which bridge but the unmaintained was replaced by 

https://github.com/discourse/discourse-code-review

example 
https://review.discourse.org

**Comment by gobengo** [comment]
Closing because there isn't one issue tracker.
